### Create one patient
POST http://localhost:4000/api/patient
Content-Type: application/json

{
    "name": "Cynthia",
    "nric": "1234503",
    "gender": "F",
    "age": 61,
    "bloodType": "O",
    "allergy": ["nuts"],
    "medicalCondition": "G6PD"
}

### Read one patient
GET  http://localhost:4000/api/patient/61bc315f52b377b7c8c1e4f3

### Read all patients
GET http://localhost:4000/api/patient/all

### Update one patient
PUT  http://localhost:4000/api/patient/61bc31cd52b377b7c8c1e4f6
Content-Type: application/json

{
    "name": "Arianna",
    "id": "1234502",
    "gender": "F",
    "age": 21,
    "bloodType": "A+",
    "allergy": [],
    "medicalCondition": "healthy"
}

### Delete one patient 
DELETE  http://localhost:4000/api/patient/61bc31cd52b377b7c8c1e4f0

### Delete all patients
DELETE   http://localhost:4000/api/patient/cleardata

### Seed patients
POST http://localhost:4000/api/patient/seed