### Create Request
POST http://localhost:4000/api/staff
Content-Type: application/json

### Read Request

### Update Request

### Delete Patient Request

### Clear Database
DELETE   http://localhost:4000/api/staff/cleardata

### Seed Data
POST http://localhost:4000/api/staff/seed