### Create Request
POST http://localhost:4000/staff
Content-Type: application/json



### Read Request

### Update Request

### Delete Patient Request

### clear database
DELETE   http://localhost:4000/staff/cleardata

### Seed data

POST http://localhost:4000/staff/seed

