const patientData = [
  {
    name: 'Cynthia',
    nric: '1234503',
    gender: 'F',
    age: 61,
    bloodType: 'O',
    allergy: ['nuts'],
    medicalCondition: 'G6PD',
  },
  {
    name: 'Lilia',
    nric: '1234503',
    gender: 'F',
    age: 61,
    bloodType: 'O',
    allergy: ['nuts', 'prawn'],
    medicalCondition: 'G6PD',
  },
  {
    name: 'Winson',
    nric: '1234999',
    gender: 'M',
    age: 59,
    bloodType: 'A',
    allergy: ['seafood', 'prawn'],
    medicalCondition: 'G6PD',
  },
  {
    name: 'Ling',
    nric: '1234889',
    gender: 'M',
    age: 44,
    bloodType: 'B',
    allergy: ['cake', 'wine'],
    medicalCondition: 'G6PD',
  },
  {
    name: 'Hakeym',
    nric: '1234689',
    gender: 'M',
    age: 36,
    bloodType: 'A',
    allergy: ['peanut', 'alchol'],
    medicalCondition: 'G6PD',
  },
];
