const staffData = [
  {
    loginID: 'chief',
    password: 'chief123',
    NRIC: 'S1234567J',
    name: 'Chief',
    gender: 'F',
    contact: 12378,
    role: 'Chief',
    speciality: ['general'],
  },
  {
    loginID: 'kienwei',
    password: 'kienwei',
    NRIC: 'S1234568J',
    name: 'Kien Wei',
    gender: 'M',
    contact: 12378,
    role: 'Doctor',
    speciality: ['general'],
  },
  {
    loginID: 'weilun',
    password: 'weilun',
    NRIC: 'S1235568J',
    name: 'Wei Lun',
    gender: 'M',
    contact: 22378,
    role: 'Doctor',
    speciality: ['urology'],
  },
  {
    loginID: 'wenjie',
    password: 'wenjie',
    NRIC: 'S1535568J',
    name: 'Wen Jie',
    gender: 'M',
    contact: 27378,
    role: 'Doctor',
    speciality: ['neurological'],
  },

  {
    loginID: 'dexter',
    password: 'dexter',
    NRIC: 'S1234569J',
    name: 'Dexter',
    gender: 'M',
    contact: 12378,
    role: 'Doctor',
    speciality: ['otolaryngology'],
  },

  {
    loginID: 'yihui',
    password: 'yihui',
    NRIC: 'S1234519J',
    name: 'Yi Hui',
    gender: 'F',
    contact: 12371,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'siewla',
    password: 'siewla',
    NRIC: 'S1234529J',
    name: 'Siew La',
    gender: 'F',
    contact: 12331,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'arianne',
    password: 'arianne',
    NRIC: 'S1909529J',
    name: 'Arianne',
    gender: 'F',
    contact: 12439,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'cynthia',
    password: 'cynthia',
    NRIC: 'S1911529J',
    name: 'Cynthia',
    gender: 'F',
    contact: 12039,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'lea',
    password: 'lea',
    NRIC: 'S1001529J',
    name: 'Lea',
    gender: 'F',
    contact: 10039,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'browne',
    password: 'browne',
    NRIC: 'S1001929J',
    name: 'Browne',
    gender: 'F',
    contact: 10099,
    role: 'Nurse',
    speciality: ['general'],
  },
  {
    loginID: 'zendeya',
    password: 'zendeya',
    NRIC: 'S1001429J',
    name: 'Zendeya',
    gender: 'F',
    contact: 10019,
    role: 'Nurse',
    speciality: ['general'],
  },
];

module.exports = staffData;
