const patientData = [
  {
    name: 'Aubrey',
    nric: 'F1234503B',
    gender: 'F',
    age: 61,
    bloodType: 'AB',
    allergy: ['nuts'],
    medicalCondition: 'ligament injury',
  },
  {
    name: 'Lilia',
    nric: 'T1234506A',
    gender: 'F',
    age: 61,
    bloodType: 'O',
    allergy: ['nuts', 'prawn'],
    medicalCondition: 'heart failure',
  },
  {
    name: 'Winson',
    nric: 'S1234999C',
    gender: 'M',
    age: 59,
    bloodType: 'A+',
    allergy: ['seafood'],
    medicalCondition: 'epilepsy',
  },
  {
    name: 'Ling',
    nric: 'S1234889D',
    gender: 'M',
    age: 44,
    bloodType: 'B-',
    allergy: ['alcohol'],
    medicalCondition: 'tuberculosis',
  },
  {
    name: 'Brady',
    nric: 'S1234689E',
    gender: 'M',
    age: 36,
    bloodType: 'A+',
    allergy: ['pollen'],
    medicalCondition: 'pneumonia',
  },
  {
    name: 'Ravi',
    nric: 'S1234690F',
    gender: 'M',
    age: 44,
    bloodType: 'AB',
    allergy: ['pet'],
    medicalCondition: 'Dementia',
  },
  {
    name: 'Zunairah',
    nric: 'G1234691B',
    gender: 'F',
    age: 21,
    bloodType: 'B',
    allergy: ['milk'],
    medicalCondition: 'pneumonia',
  },
  {
    name: 'Aneeka',
    nric: 'M1234692G',
    gender: 'F',
    age: 70,
    bloodType: 'B',
    allergy: ['egg'],
    medicalCondition: 'Down syndrome',
  },
  {
    name: 'Haya',
    nric: 'S1234693H',
    gender: 'F',
    age: 32,
    bloodType: 'A',
    allergy: ['soy'],
    medicalCondition: 'Cancer',
  },
  {
    name: 'Diana',
    nric: 'S1234694I',
    gender: 'F',
    age: 51,
    bloodType: 'A',
    allergy: ['wheat'],
    medicalCondition: 'Chronic kidney disease',
  },
  {
    name: 'Gregor',
    nric: 'T1234695J',
    gender: 'M',
    age: 5,
    bloodType: 'B',
    allergy: ['-'],
    medicalCondition: 'Chronic liver disease',
  },
  {
    name: 'Abigale',
    nric: 'T1234696K',
    gender: 'f',
    age: 12,
    bloodType: 'A',
    allergy: ['-'],
    medicalCondition: 'Asthma',
  },
  {
    name: 'Huw Lawrence',
    nric: 'S1234697L',
    gender: 'M',
    age: 46,
    bloodType: 'O',
    allergy: ['-'],
    medicalCondition: 'Bronchiectasis',
  },
  {
    name: 'Kathryn Ritter',
    nric: 'S1234698M',
    gender: 'F',
    age: 39,
    bloodType: 'B',
    allergy: ['-'],
    medicalCondition: 'Cystic fibrosis',
  },
  {
    name: 'Chris Alford',
    nric: 'S1234699N',
    gender: 'M',
    age: 63,
    bloodType: 'A',
    allergy: ['-'],
    medicalCondition: 'Diabetes',
  },
  {
    name: 'Tyra Ireland',
    nric: 'F1234700P',
    gender: 'F',
    age: 49,
    bloodType: 'A',
    allergy: ['-'],
    medicalCondition: 'HIV Infection',
  },
  {
    name: 'Maci Lloyd',
    nric: 'G1234701Q',
    gender: 'F',
    age: 13,
    bloodType: 'O',
    allergy: ['Antibiotics'],
    medicalCondition: 'Heart Disease',
  },
  {
    name: 'Eesha Parker',
    nric: 'S1234702R',
    gender: 'F',
    age: 27,
    bloodType: 'B+',
    allergy: ['Aspirin'],
    medicalCondition: 'immunodeficiency',
  },
  {
    name: 'Cordelia Gray',
    nric: 'S9134689C',
    gender: 'F',
    age: 30,
    bloodType: 'B-',
    allergy: ['ibuprofen'],
    medicalCondition: '-',
  },
  {
    name: 'Jessica Lawrence',
    nric: 'S2234689V',
    gender: 'F',
    age: 31,
    bloodType: 'B',
    allergy: ['-'],
    medicalCondition: '-',
  },
  {
    name: 'Francis Ahmed',
    nric: 'S9934689Z',
    gender: 'M',
    age: 56,
    bloodType: 'AB',
    allergy: ['-'],
    medicalCondition: '-',
  },
  {
    name: 'Ailish Edwards',
    nric: 'S1734689D',
    gender: 'F',
    age: 37,
    bloodType: 'A+',
    allergy: ['-'],
    medicalCondition: '-',
  },
  {
    name: 'Humaira Stark',
    nric: 'S1834689H',
    gender: 'F',
    age: 25,
    bloodType: 'A-',
    allergy: ['-'],
    medicalCondition: '-',
  },
  {
    name: 'Leia Dawe',
    nric: 'S1934689J',
    gender: 'F',
    age: 22,
    bloodType: 'O',
    allergy: ['-'],
    medicalCondition: '-',
  },
  {
    name: 'Piotr Sierra',
    nric: 'S1454689K',
    gender: 'M',
    age: 47,
    bloodType: 'B',
    allergy: ['-'],
    medicalCondition: '-',
  },
];

module.exports = patientData;
